// This file is generated by Prismic local builder. Update with care!

export { default as BannerSlice } from "./BannerSlice";
export { default as FeaturedImage } from "./FeaturedImage";
export { default as FullWidthImage } from "./FullWidthImage";
export { default as ImageGallery } from "./ImageGallery";
export { default as QuoteSlice } from "./QuoteSlice";
export { default as TextSlice } from "./TextSlice";

import { BannerSlice } from "./BannerSlice";
import { FeaturedImage } from "./FeaturedImage";
import { FullWidthImage } from "./FullWidthImage";
import { ImageGallery } from "./ImageGallery";
import { QuoteSlice } from "./QuoteSlice";
import { TextSlice } from "./TextSlice";

export const components = {
  banner_slice: BannerSlice,
  featured_image: FeaturedImage,
  full_width_image: FullWidthImage,
  image_gallery: ImageGallery,
  quote_slice: QuoteSlice,
  text_slice: TextSlice,
};
