// Code generated by Prismic. DO NOT EDIT.

import Hero from "./Hero";
import Image from "./Image";
import ImageCards from "./ImageCards";
import Quote from "./Quote";
import Text from "./Text";
import TextWithImage from "./TextWithImage";

export const components = {
  hero: Hero,
  image: Image,
  image_cards: ImageCards,
  quote: Quote,
  text: Text,
  text_with_image: TextWithImage,
};
